# Generated by Django 4.0.5 on 2022-06-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('ram', models.CharField(max_length=40)),
                ('rom', models.CharField(max_length=40)),
                ('hdd', models.CharField(max_length=40)),
                ('ssd', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
    ]
